### ISSUE TITLE
May 6, Instructor consultations

### ISSUE THREAD

**Issue by rickecon** [UC-MACSS/persp-research-econ_Spr19#2]
Dear MACS 30250 Perspectives on Computational Economics Research students,

I have posted a [schedule of available times](https://github.com/UC-MACSS/persp-research-econ_Spr19/blob/master/OfficeVisits/README.md) for your Monday, May 6 office consultations with me. These consultations will be held instead of class on Monday, May 6. Each of you will have 10 minutes with me in which we can discuss and assess:
* Your progress on your paper
* Any issues you might be having
* Any suggestions from Dr. Evans
Please respond to this issue with the time you would prefer.

@boyangqu, @dongchengecon, @fulinguo, @HaowenShang, @jsgenan, @jtschoi, @keertanavc, @liu431, @nt546, @ruixili, @sergioservan, @SixueLiuMACSS, @SiyuanPengMike, @sunying2018, @TianxinZheng, @yalingtsui, @zeyuxu1997

**Comment by SiyuanPengMike** [comment]
Shall I visit at 2:40 PM?

**Comment by jsgenan** [comment]
Nan Ge 2:30 PM

**Comment by zeyuxu1997** [comment]
Zeyu Xu 2:20 PM

**Comment by sunying2018** [comment]
Ying Sun 2:50PM

**Comment by ruixili** [comment]
Ruixi Li 3:00 PM

**Comment by dongchengecon** [comment]
Dongcheng Yang 3:10 PM

**Comment by SixueLiuMACSS** [comment]
Sixue Liu 3:00pm

**Comment by jtschoi** [comment]
Junho Choi 4:00 PM

**Comment by SixueLiu96** [comment]
Sixue Liu 3:20pm

**Comment by HaowenShang** [comment]
Haowen Shang 3:30pm

**Comment by TianxinZheng** [comment]
Tianxin Zheng 4:10

**Comment by boyangqu** [comment]
Boyang Qu 3:40pm

**Comment by keertanavc** [comment]
Keertana Chidambaram 1:30 pm

**Comment by liu431** [comment]
Li Liu 1:40pm

**Comment by fulinguo** [comment]
Fulin Guo 2:10pm

**Comment by rickecon** [comment]
@jtschoi Can I put you at 1:50p instead?

**Comment by rickecon** [comment]
@TianxinZheng Can I put you at 2:00p instead?

**Comment by TianxinZheng** [comment]
@rickecon Yeah I'm fine.

**Comment by rickecon** [comment]
Thanks, @TianxinZheng. I've made the change on the schedule and put you at 2:00pm.

**Comment by sergioservan** [comment]
Sergio: 3:50 pm

**Comment by nt546** [comment]
Nipun Thakurele 4:10 pm
